
project_id = "itlowkvfixpquzgoylqc"

[api]
enabled = true
port = 54321
schemas = []

[db]
port = 54322

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
