// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itlowkvfixpquzgoylqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bG93a3ZmaXhwcXV6Z295bHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0Nzc2OTYsImV4cCI6MjA1ODA1MzY5Nn0.Lu95DBEDM0HCvXxTjm3CsHxG3Glr_1pimYlrF51Cfyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);